import Head from 'next/head'
import Image from 'next/image'
import Experience from '../Components/Experience/Experience'
import Experties from '../Components/Experties/Experties'
import Feedback from '../Components/Feedback/Feedback'
import Footer from '../Components/Footer/Footer'
import Foots from '../Components/Footer/foots'
import Header from '../Components/Header/Header'
import Banner from '../Components/Landing/Banner'
import Landing from '../Components/Landing/Landing'
import Osama from '../Components/Landing/Osama'
import Project from '../Components/Project/Project'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Landing/>
      <Experties/>
      <Experience/>
      <Project/>
      <Feedback/>
      <Footer/>
      </div>
      <Foots/>
    </div>
  )
}
